In [ ]:
# Step 1
# Importing the necessary libraries
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

# Step 2
# Loading the dataset
dataset = load_wine()

# Step 3
# Splitting the data into tst and train
# 80 - 20 Split
x_train, x_test, y_train, y_test = train_test_split(dataset.data, dataset.target, test_size=0.20, random_state=4)

# Step 4
# Making the Neural Network Classifier
NN = MLPClassifier()

# Step 5
# Training the model on the training data and labels
NN.fit(x_train, y_train)

# Step 6
# Testing the model i.e. predicting the labels of the test data.
y_pred = NN.predict(x_test)

# Step 7
# Evaluating the results of the model
accuracy = accuracy_score(y_test,y_pred)*100
confusion_mat = confusion_matrix(y_test,y_pred)

# Step 8
# Printing the Results
print("Accuracy for Neural Network is:",accuracy)
print("Confusion Matrix")
print(confusion_mat)
print(classification_report
      (y_test,y_pred))



Accuracy for Neural Network is: 91.66666666666666
Confusion Matrix
[[10  0  0]
 [ 1 12  0]
 [ 1  1 11]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.92      0.92      0.92        13
           2       1.00      0.85      0.92        13

    accuracy                           0.92        36
   macro avg       0.92      0.92      0.92        36
weighted avg       0.93      0.92      0.92        36



/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
